### ISSUE TITLE
Alterações no perfil

### ISSUE THREAD

**Issue by danielmoreira123** [Brunofgm7/Workout-Website#3]
Quando se guarda as alterações no perfil, dá um erro.
As alterações em si são feitas corretamente, só dá é um erro quando clicas no botão Guardar.

**Comment by NunoDias98** [comment]
Podes dar mais informação para tentar perceber qual é o problema.

**Comment by danielmoreira123** [comment]
Quando clico no botão guardar, para alterar os dados, vai-me para um URL desconhecido.

**Comment by danielmoreira123** [comment]
Já vi o problema, quando clico no botao vai para a pasta "workout-website" e eu tinha a minha com o nome "Workout-website-master".
A minha solução para o vosso problema seria colocar no Read-me o nome da pasta necessário.

**Comment by Brunofgm7** [comment]
Corrigido! Obrigado!

**Comment by NunoDias98** [comment]
Updated the file "upload.php".
